# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Restrict Podfile Update

on:
  push:
    branches:
      - main

jobs:
  grant-permissions:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Grant permissions
      run: echo "The restricted file was updated."
     


      
